apps/bootcamp_courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name= 'index'),
    url(r'^create$', views.create, name='add_course'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name='remove_course'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete_course'),
  ]

courses/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^',include('apps.bootcamp_courses.urls', namespace='home')),
]

apps/bootcamp_courses/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Course(models.Model):
    course_name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/bootcamp_courses/views.py
from django.shortcuts import render, redirect
from .models import Course

# Create your views here.
def index(request):
    context = {
       'all_courses': Course.objects.all(),

    }
    return render(request, 'bootcamp_courses/index.html', context)

def create(request):
    if request.method == 'POST':
        Course.objects.create(course_name = request.POST['course_name'], description=request.POST['description'])
    return redirect('/')

def remove(request, id):
    context = {
         'course': Course.objects.get(id= id)
    }
    return render(request, 'bootcamp_courses/remove.html', context)

def delete(request, id):
    this = Course.objects.get(id= id)
    this.delete()
    return redirect('/')

apps/bootcamp_courses/templates/bootcamp_courses/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Courses</title>

  </head>
  <body>

    <div class="container1">
      <h2>Add a new course</h2>
      <form class="" action="{% url 'home:add_course' %}" method="post">
         {% csrf_token %}
         Name: <input type="text" name="course_name" value=""><br>
         Description: <input type="text" name="description" value=""><br>
         <input type="submit" name="" value="ADD">
      </form>
    </div>

    <div class="container2">
      <h2>Courses</h2>
      <table class= "table">
        <tr>
           <th>Course Name</th>
           <th>Description</th>
           <th>Date Added</th>
           <th>Actions</th>
        </tr>
        {% for course in all_courses %}
        <tr>
          <td>{{ course.course_name }}</td>
          <td>{{ course.description }}</td>
          <td>{{ course.created_at }}</td>
          <td>
               <form class="" action="{% url 'home:remove_course' course.id %}" method="post">
                 {% csrf_token %}
                  <input type="hidden" name="course_id" value="{{ course.id }}">
                  <input type="submit" name="" value="REMOVE">
               </form>
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </body>
</html>

apps/bootcamp_courses/templates/bootcamp_courses/remove.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Are you sure you want to delete the following course?</h1>
      Name: {{ course.course_name}}<br>
      Description: {{course.description}}
      <form class="" action="{% url 'home:index' %}" method="post">
        {% csrf_token %}
          <input type="submit" name="" value="NO">
      </form>
      <form class="" action="{% url 'home:delete_course' course.id %}" method="post">
        {% csrf_token %}
          <input type="submit" name="" value="Yes, I want to delete this">
      </form>
  </body>
</html>